"""Init.

Revision ID: 59eacaa4aaf1
Revises: 
Create Date: 2015-10-28 14:57:58.918735

"""

# revision identifiers, used by Alembic.
revision = '59eacaa4aaf1'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('link_nodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    op.create_table('link_node_card_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('channel_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('faults',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('z_position', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('fault_inputs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fault_id', sa.Integer(), nullable=False),
    sa.Column('bit_position', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['fault_id'], ['faults.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('device_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fault_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('fault_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fault_id'], ['faults.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('link_node_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('link_node_id', sa.Integer(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['link_node_id'], ['link_nodes.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['link_node_card_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('link_node_channels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['link_node_cards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('device_inputs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('bit_position', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['link_node_channels.id'], ),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('device_inputs')
    op.drop_table('link_node_channels')
    op.drop_table('link_node_cards')
    op.drop_table('fault_states')
    op.drop_table('device_states')
    op.drop_table('fault_inputs')
    op.drop_table('devices')
    op.drop_table('faults')
    op.drop_table('link_node_card_types')
    op.drop_table('link_nodes')
    ### end Alembic commands ###
