# Disable all thresholds
- mmio:
  - AmcCarrierCore:
    - AppMps:
      - AppMpsRegAppCh:
        - channel:
          - idleEn: !<value> 0x0
          - lcls1Thr:
            - minEn: !<value> 0x0
            - maxEn: !<value> 0x0
            - min:   !<value> 0x0
            - max:   !<value> 0x0
          - stdThr:
            - minEn: !<value> 0x0
            - maxEn: !<value> 0x0
            - min:   !<value> 0x0
            - max:   !<value> 0x0
          - idleThr:
            - minEn: !<value> 0x0
            - maxEn: !<value> 0x0
            - min:   !<value> 0x0
            - max:   !<value> 0x0
          - altThr:
            - minEn: !<value> 0x0
            - maxEn: !<value> 0x0
            - min:   !<value> 0x0
            - max:   !<value> 0x0
# Analog application AppID
- mmio:
  - AmcCarrierCore: 
    - AppMps:
      - AppMpsRegBase:
        - mpsAppId: !<value> 219


- mmio:
  - AppTop:
    - AppCore:
      - MpsAnalogCore:
        - MpsAnalogLcls1Reg:
          - PrcValueSelect: !<value> 3
        - MpsAnalogLcls2Reg:
          - PrcValueSelect: !<value> 3
#Analog Processing Settings
- mmio:
  - AppTop:
    - AppCore:
      - MpsAnalogCore:
        - MpsAnalogLcls2Reg:
          - InputDisable: !<value> 2
- mmio:
  - AppTop:
    - AppCore:
      - MpsAnalogCore:
        - MpsAnalogLcls1Reg:
          - InputDisable: !<value> 2
- mmio:
  - AmcCarrierCore:
    - AppMps:
        - AppMpsSalt: 
          - MpsChEnable: !<value> 0x3e
