from sqlalchemy import Column, Integer, String, ForeignKey
from sqlalchemy.orm import relationship, backref
from mps_database.models import Base

class ConditionInput(Base):
  """
  ConditionInput class (condition_inputs table)

  Defines one input for a Condition. If the ConditionInput is true, then
  the Condition evaluation value at the specified bit_position is set.

  The input is given by the FaultState referenced by fault_state_id. The
  FaultState defines which DeviceState causes a Fault to be true. The Fault
  has indirect references (via FaultInput/Device) to a device (e.g. YAG01B or
  OTRDMP), so a ConditionInput refers to faults generated by specific devices.

  Properties:
    bit_position: the position for the fault state within the condition value

  References:
    fault_state_id: reference to the fault_state, which if true makes this 
                    condition also true.
    condition_id:
  """
  __tablename__ = 'condition_inputs'
  id = Column(Integer, primary_key=True)
  bit_position = Column(Integer, nullable=False)
  fault_state_id = Column(Integer, ForeignKey('fault_states.id'), nullable=False)
  condition_id = Column(Integer, ForeignKey('conditions.id'), nullable=False)
