- mmio:
  - AmcCarrierCore:
    - AppMps:
        - AppMpsSalt: 
          - MpsChEnable: !<value> 0x3e
# Analog application AppID
- mmio:
  - AppTop:
    - AppCore:
      - MpsLinkNodeCore:
        - UdpBroadcastIP: !<value> 4294967295
        - MpsLcls1Core:
          - NodeId: !<value> 77
          - IpAddr: !<value> 1291888832
          - appIdRemap[0]: !<value> 0
          - appIdRemap[1]: !<value> 123
          - appIdRemap[2]: !<value> 0
          - appIdRemap[3]: !<value> 0
          - appIdRemap[4]: !<value> 0
          - appIdRemap[5]: !<value> 0
          - appIdRemap[6]: !<value> 122
          - appIdRemap[7]: !<value> 0
          - appIdRemap[8]: !<value> 0
          - appIdRemap[9]: !<value> 0
          - appIdRemap[10]: !<value> 0
          - TimeoutMask: !<value> 64
          - TimeoutEnable: !<value> 1
          - TimeoutTime: !<value> 7

# Digital application AppID
- mmio:
  - AppTop:
    - AppCore:
      - MpsLinkNodeCore:
        - MpsDigitalMessage:
          - AppId: !<value> 121
# Disable all thresholds
- mmio:
  - AmcCarrierCore:
    - AppMps:
      - AppMpsRegAppCh:
        - channel:
          - idleEn: !<value> 0x0
          - lcls1Thr:
            - minEn: !<value> 0x0
            - maxEn: !<value> 0x0
            - min:   !<value> 0x0
            - max:   !<value> 0x0
          - stdThr:
            - minEn: !<value> 0x0
            - maxEn: !<value> 0x0
            - min:   !<value> 0x0
            - max:   !<value> 0x0
          - idleThr:
            - minEn: !<value> 0x0
            - maxEn: !<value> 0x0
            - min:   !<value> 0x0
            - max:   !<value> 0x0
          - altThr:
            - minEn: !<value> 0x0
            - maxEn: !<value> 0x0
            - min:   !<value> 0x0
            - max:   !<value> 0x0
# Analog application AppID
- mmio:
  - AmcCarrierCore: 
    - AppMps:
      - AppMpsRegBase:
        - mpsAppId: !<value> 122


- mmio:
  - AppTop:
    - AppCore:
      - MpsAnalogCore:
        - MpsAnalogLcls1Reg:
          - PrcValueSelect: !<value> 3
        - MpsAnalogLcls2Reg:
          - PrcValueSelect: !<value> 3
#Analog Processing Settings
- mmio:
  - AppTop:
    - AppCore:
      - MpsAnalogCore:
        - MpsAnalogLcls2Reg:
          - InputDisable: !<value> 2
- mmio:
  - AppTop:
    - AppCore:
      - MpsAnalogCore:
        - MpsAnalogLcls1Reg:
          - InputDisable: !<value> 2
